# Base information
baseURL = "https://jrn-ds.net"
languageCode = "en-us"
title = "José Robles Noriega"
theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Remove this when using normally
#themesDir = "/theme/"
#themesDir = "/theme"
# `
#[module]
#  [[module.imports]]
#    path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

#  [[menu.main]]
#  name = "Blog"
#  URL = "blog"
#  weight=2

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=3


[params]
home = "Home"
# Meta data
description = "The website of José Robles, Data Scientist in located in Mexico City"
author = "José Robles"
project1 = "income_model_r_version"

  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "jose.robles.noriega@gmail.com"
  address = "Mexico City"
  googlemaps = "https://www.google.com.mx/maps/@19.4250878,-99.1736431,16z"
  year = "2022"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4
